<a href="https://colab.research.google.com/github/shailza969/Iris-data-ML/blob/main/Decision_tree_%26_Random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
iris_df = pd.read_csv('/content/Iris.csv')

In [ ]:
iris_df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_sp = LabelEncoder()

In [ ]:
iris_df['Species'] = le_sp.fit_transform(iris_df['Species'])

In [ ]:
iris_df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [ ]:
le_sp.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
X = iris_df.iloc[:, 1:5]
y = iris_df.iloc[:, 5]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [ ]:
X = sc.fit_transform(X)

In [ ]:
X[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

# DECISION TREE

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion ='entropy', max_depth = 3, max_leaf_nodes= 3)

In [ ]:
clf.fit(X_train,y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features=None, max_leaf_nodes=3,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred = clf.predict(X_train)
y_pred2 = clf.predict(X_test)
clf.score(X_train, y_train)

0.9666666666666667

In [ ]:

clf.score(X_test, y_test)

0.9333333333333333

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_pred, y_train))
print(confusion_matrix(y_pred2, y_test))

[[37  0  0]
 [ 0 44  3]
 [ 0  1 35]]
[[13  0  0]
 [ 0  5  2]
 [ 0  0 10]]


# RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
clf1 = RandomForestClassifier(n_estimators=100, n_jobs = -1, max_depth = 3, oob_score=True)

In [ ]:
clf1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=True, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:
y_pred3 = clf1.predict(X_train)

In [ ]:
clf1.score(X_train, y_train)

0.9583333333333334

In [ ]:
clf1.score(X_test, y_test)

0.9333333333333333

# SVM

In [ ]:
from sklearn.svm import SVC
ss= SVC()

In [ ]:
ss.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
ss.score(X_train, y_train)

0.975

In [ ]:
ss.score(X_test, y_test)

0.9666666666666667